# Schema for the configuration files of the Color Fied module.

# Widget.
entity_form_display.field.color_field_default:
  type: entity_field_form_display_base
  label: 'Telephone default format settings'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        placeholder_color:
          type: label
          label: 'Placeholder for the color property'
        placeholder_opacity:
          type: label
          label: 'Placeholder for the opacity property'

# Formater.
entity_view_display.field.color_field_swatch:
  type: entity_field_view_display_base
  label: 'Telephone link format settings'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        title:
          type: label
          label: 'Title to replace basic numeric telephone number display'

# Formater.
entity_view_display.field.color_field_text:
  type: entity_field_view_display_base
  label: 'Telephone link format settings'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        title:
          type: label
          label: 'Title to replace basic numeric telephone number display'
